### PR TITLE
Added daily metrics

### PR DESCRIPTION
**Pull request by Misanthropik**
* Monitor your daily metrics now alongside lifetime.
* Automatic and manual reset functions for daily metrics.

### CODE REVIEW

**Review by shokobata — COMMENTED** [review]
I am thankful that someone cared about my project enough to do that. I will be testing your code for a bit and see if it is the same as the vision I have for this project.

**Comment by Misanthropik** [comment]
Updated to V11, do check the code and let me know what you think,  it should be cleaner now.

**Review by shokobata — APPROVED** [review]

**Comment by shokobata** [comment]
Hi, would you like to work with me on this project? If so then please comment your contact info(preferably discord) so that we can discuss this matter further.

**Comment by Misanthropik** [comment]
My discord username is `Misanthropic#4984`

**Comment by shokobata** [comment]
I sent a friend request. I am Overloaded L.E.D

**Pull request merged**
